version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dotnet:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: "/F1Predictor.Web"
    schedule:
      interval: weekly
    groups:
      next:
        patterns: ["next", "eslint-config-next"]
      react:
        patterns: ["react", "react-dom", "@types/react", "@types/react-dom"]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
