/** Mirrors `AiStatusResponse` — `GET /api/ai/status`. */
export interface AiStatusResponse {
  /** Whether narrative generation and the analyst chat are on. */
  chatAvailable: boolean;
  /** Reserved for semantic search; always false for now. */
  embeddingsAvailable: boolean;
  /** "None", "Ollama" or "OpenAi". */
  provider: string;
  /** Chat model name, or null when chat is unavailable. */
  model: string | null;
  /** Embedding model name, or null. */
  embeddingModel: string | null;
}

/** Mirrors `RacePreviewResponse` — `GET`/`POST /api/races/{sessionKey}/preview`. */
export interface RacePreviewResponse {
  sessionKey: number;
  meetingName: string;
  /** True when written from the real starting grid; false when from a grid projected from form. */
  gridConfirmed: boolean;
  /** The chat model that wrote the preview. */
  model: string;
  generatedAt: string;
  /** Taken from the body's first markdown heading. */
  headline: string;
  /** The full markdown body. */
  content: string;
  /** True when the grid or results have moved on since this was written. */
  stale: boolean;
}

export type ContributionDirection = "helps" | "hurts" | "neutral";

/** Mirrors `FeatureContributionResponse`. */
export interface FeatureContribution {
  /** Feature name as the model knows it, e.g. "GridPosition". */
  feature: string;
  /** The raw feature value that was fed in. */
  value: number;
  /** Contribution to the target's raw score. */
  contribution: number;
  direction: ContributionDirection;
}

/** Mirrors `TargetExplanationResponse`. */
export interface TargetExplanation {
  /** Calibrated probability for this target. */
  probability: number;
  /** Raw model score the probability was calibrated from. */
  score: number;
  contributions: FeatureContribution[];
}

/** Mirrors `DriverExplanationResponse` — `GET /api/seasons/{year}/next-race/drivers/{driverNumber}/explanation`. */
export interface DriverExplanationResponse {
  sessionKey: number;
  meetingName: string;
  gridConfirmed: boolean;
  driverNumber: number;
  fullName: string;
  nameAcronym: string;
  teamName: string;
  teamColour: string;
  podium: TargetExplanation;
  pointsFinish: TargetExplanation;
  /** Reserved for a future holdout comparison; always null for a next-race explanation. */
  finishPosition: number | null;
  actualPodium: boolean | null;
  actualPointsFinish: boolean | null;
  /** A short AI narrative of the contributions, or null when no AI provider is configured or it failed. */
  narrative: string | null;
  /** The chat model that produced `narrative`, or null when there is none. */
  model: string | null;
}

/** SSE event names on `POST /api/ai/ask`; `data` carries the same value as `type`. */
export type AnalystEventType = "status" | "delta" | "done" | "error";

/** Mirrors `AnalystEvent`. */
export interface AnalystEvent {
  type: AnalystEventType;
  text: string | null;
}

/** Mirrors `ChatTurn` — one message in the conversation sent to the analyst. */
export interface ChatTurn {
  role: "user" | "assistant";
  content: string;
}

/** Mirrors `RefreshAnalysisResponse` — `POST /api/admin/analysis/refresh?year=`. */
export interface RefreshAnalysisResponse {
  /** Race previews (re)generated by this run. */
  previewsGenerated: number;
  /** Always 0 for now — reserved for a future semantic-search index step. */
  racesIndexed: number;
  /** Years or races left untouched: no upcoming race to preview, or an already-fresh preview. */
  skipped: number;
  /** Human-readable detail for anything that didn't simply succeed or skip cleanly. */
  notes: string[];
}
