namespace F1Predictor.Application.Features.Analysis.RefreshAnalysis;

/// <param name="PreviewsGenerated">Race previews (re)generated by this run.</param>
/// <param name="RacesIndexed">
/// Always 0 for now — this handler only refreshes previews. A later task extends it to index
/// newly classified races for semantic search.
/// </param>
/// <param name="Skipped">
/// Years or races left untouched: no upcoming race to preview, or an existing preview that was
/// already fresh.
/// </param>
/// <param name="Notes">Human-readable detail for anything that didn't simply succeed or skip cleanly.</param>
public sealed record RefreshAnalysisResponse(
    int PreviewsGenerated,
    int RacesIndexed,
    int Skipped,
    IReadOnlyList<string> Notes);
