namespace F1Predictor.Application.Features.Analysis.RefreshAnalysis;

/// <param name="PreviewsGenerated">Race previews (re)generated by this run.</param>
/// <param name="RacesIndexed">
/// Races actually re-embedded by this run — 0 when embeddings are unavailable, or when every
/// classified race in scope was already indexed under an unchanged fact sheet and model.
/// </param>
/// <param name="Skipped">
/// Years or races left untouched: no upcoming race to preview, or an existing preview that was
/// already fresh.
/// </param>
/// <param name="Notes">Human-readable detail for anything that didn't simply succeed or skip cleanly.</param>
public sealed record RefreshAnalysisResponse(
    int PreviewsGenerated,
    int RacesIndexed,
    int Skipped,
    IReadOnlyList<string> Notes);
