"use client";

import { useCallback } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { generateRacePreview, getRacePreview } from "@/features/analysis/analysis-service";
import { Button } from "@/shared/components/Button";
import { Card } from "@/shared/components/Card";
import { ErrorBanner } from "@/shared/components/ErrorBanner";
import { Skeleton } from "@/shared/components/Skeleton";
import { StatusAnnouncer } from "@/shared/components/StatusAnnouncer";
import { getErrorDisplay } from "@/shared/lib/error-display";
import { useAiStatus } from "@/shared/lib/use-ai-status";
import { useAsyncAction } from "@/shared/lib/use-async-action";
import { useLiveData } from "@/shared/lib/use-live-data";

interface RacePreviewNarrativeProps {
  sessionKey: number;
}

/** A stored preview only changes when someone regenerates it, so this polls far less often than the numbers. */
const PREVIEW_REFRESH_MS = 5 * 60_000;

/** No typography plugin here, so the markdown gets a small set of spacing rules on its wrapper. */
const MARKDOWN_CLASSES =
  "text-sm leading-relaxed [&_p]:my-2 [&_ul]:my-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ol]:my-2 [&_ol]:list-decimal [&_ol]:pl-5 [&_li]:my-0.5 [&_strong]:font-semibold [&_h1]:mt-4 [&_h1]:text-base [&_h1]:font-semibold [&_h2]:mt-4 [&_h2]:text-base [&_h2]:font-semibold [&_h3]:mt-3 [&_h3]:text-sm [&_h3]:font-semibold [&_a]:underline [&_code]:font-mono [&_code]:text-xs [&_table]:my-2 [&_table]:text-xs [&_th]:pr-3 [&_th]:text-left [&_td]:pr-3 [&>*:first-child]:mt-0 [&>*:last-child]:mb-0";

/**
 * The backend lifts the headline out of the body's first heading but leaves it in the body,
 * so it is dropped here rather than rendered twice.
 */
function bodyWithoutHeadline(content: string): string {
  const lines = content.split("\n");
  const headingIndex = lines.findIndex((line) => line.trim().startsWith("#"));

  return headingIndex === -1 ? content : lines.filter((_, index) => index !== headingIndex).join("\n");
}

export function RacePreviewNarrative({ sessionKey }: RacePreviewNarrativeProps) {
  const fetcher = useCallback(() => getRacePreview(sessionKey), [sessionKey]);
  const { data, error, loading, refresh } = useLiveData(fetcher, [sessionKey], PREVIEW_REFRESH_MS);
  const { chatAvailable } = useAiStatus();

  const { status, error: generateError, run } = useAsyncAction(async () => {
    const preview = await generateRacePreview(sessionKey);
    refresh();
    return preview;
  });

  const generating = status === "running";
  const notFound = error?.code === "Analysis.PreviewNotFound";

  const announcement =
    status === "success"
      ? "Race preview generated."
      : status === "error" && generateError
        ? `Preview generation failed: ${generateError.message}`
        : null;

  if (loading) {
    return (
      <Card title="AI race preview">
        <div className="space-y-2" role="status" aria-label="Loading race preview">
          <Skeleton className="h-5 w-2/3" />
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-11/12" />
        </div>
      </Card>
    );
  }

  if (error && !notFound) {
    const { title, message } = getErrorDisplay(error);

    return (
      <Card title="AI race preview">
        <ErrorBanner title={title} message={message} />
      </Card>
    );
  }

  return (
    <Card title="AI race preview">
      {notFound || !data ? (
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-sm text-(--color-muted)">No preview generated yet.</p>
          {chatAvailable && (
            <Button onClick={() => run()} disabled={generating} aria-busy={generating}>
              {generating ? "Generating…" : "Generate"}
            </Button>
          )}
        </div>
      ) : (
        <div>
          <div className="flex flex-wrap items-start justify-between gap-2">
            <h3 className="text-base font-semibold">{data.headline}</h3>
            {data.stale && (
              <span
                className="rounded-(--radius) bg-(--color-podium)/15 px-2 py-0.5 font-mono text-[10px] uppercase tracking-wider text-(--color-podium)"
                title="The grid or results have changed since this was written"
              >
                stale
              </span>
            )}
          </div>

          <div className={`mt-2 ${MARKDOWN_CLASSES}`}>
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{bodyWithoutHeadline(data.content)}</ReactMarkdown>
          </div>

          <div className="mt-4 flex flex-col gap-3 border-t border-(--color-border) pt-3 sm:flex-row sm:items-center sm:justify-between">
            <p className="font-mono text-xs text-(--color-muted)">
              Generated by {data.model} · {new Date(data.generatedAt).toLocaleString()}
            </p>
            {chatAvailable && (
              <Button variant="secondary" onClick={() => run()} disabled={generating} aria-busy={generating}>
                {generating ? "Regenerating…" : "Regenerate"}
              </Button>
            )}
          </div>
        </div>
      )}

      <StatusAnnouncer message={announcement} />

      {status === "error" && generateError && (
        <p className="mt-3 text-sm text-(--color-error-text)">{generateError.message}</p>
      )}
    </Card>
  );
}
