// <auto-generated />
using System;
using F1Predictor.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace F1Predictor.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814115224_ChampionshipData")]
    partial class ChampionshipData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("F1Predictor.Domain.Predictions.DriverRaceFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AvgPitStopDuration")
                        .HasColumnType("real");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("integer");

                    b.Property<int>("FinishPosition")
                        .HasColumnType("integer");

                    b.Property<float>("GridPosition")
                        .HasColumnType("real");

                    b.Property<float>("PitStopCount")
                        .HasColumnType("real");

                    b.Property<bool>("Podium")
                        .HasColumnType("boolean");

                    b.Property<bool>("PointsFinish")
                        .HasColumnType("boolean");

                    b.Property<float>("QualiGapToPole")
                        .HasColumnType("real");

                    b.Property<float>("Rainfall")
                        .HasColumnType("real");

                    b.Property<int>("SessionKey")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionKey", "DriverNumber")
                        .IsUnique();

                    b.ToTable("DriverRaceFeatures", "public");
                });

            modelBuilder.Entity("F1Predictor.Domain.RaceData.Entities.DriverEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverNumber")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameAcronym")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("SessionKey")
                        .HasColumnType("integer");

                    b.Property<string>("TeamColour")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SessionKey", "DriverNumber")
                        .IsUnique();

                    b.ToTable("DriverEntries", "public");
                });

            modelBuilder.Entity("F1Predictor.Domain.RaceData.Entities.Meeting", b =>
                {
                    b.Property<int>("MeetingKey")
                        .HasColumnType("integer");

                    b.Property<string>("CircuitShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeetingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("MeetingKey");

                    b.HasIndex("Year");

                    b.ToTable("Meetings", "public");
                });

            modelBuilder.Entity("F1Predictor.Domain.RaceData.Entities.PitStopEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverNumber")
                        .HasColumnType("integer");

                    b.Property<double?>("LaneDuration")
                        .HasColumnType("double precision");

                    b.Property<int>("SessionKey")
                        .HasColumnType("integer");

                    b.Property<double?>("StopDuration")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SessionKey", "DriverNumber");

                    b.ToTable("PitStopEntries", "public");
                });

            modelBuilder.Entity("F1Predictor.Domain.RaceData.Entities.RaceSession", b =>
                {
                    b.Property<int>("SessionKey")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClassified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSprint")
                        .HasColumnType("boolean");

                    b.Property<int>("MeetingKey")
                        .HasColumnType("integer");

                    b.Property<int?>("QualifyingSessionKey")
                        .HasColumnType("integer");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("SessionKey");

                    b.HasIndex("DateStart");

                    b.HasIndex("MeetingKey");

                    b.HasIndex("IsSprint", "IsClassified");

                    b.ToTable("RaceSessions", "public");
                });

            modelBuilder.Entity("F1Predictor.Domain.RaceData.Entities.SessionResultEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Dnf")
                        .HasColumnType("boolean");

                    b.Property<bool>("Dns")
                        .HasColumnType("boolean");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("Dsq")
                        .HasColumnType("boolean");

                    b.Property<double>("Points")
                        .HasColumnType("double precision");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("SessionKey")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionKey", "DriverNumber");

                    b.ToTable("SessionResultEntries", "public");
                });

            modelBuilder.Entity("F1Predictor.Domain.RaceData.Entities.StartingGridEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverNumber")
                        .HasColumnType("integer");

                    b.Property<double?>("LapDuration")
                        .HasColumnType("double precision");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("SessionKey")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionKey", "DriverNumber");

                    b.ToTable("StartingGridEntries", "public");
                });

            modelBuilder.Entity("F1Predictor.Domain.RaceData.Entities.WeatherReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Rainfall")
                        .HasColumnType("double precision");

                    b.Property<int>("SessionKey")
                        .HasColumnType("integer");

                    b.Property<double>("TrackTemperature")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SessionKey");

                    b.ToTable("WeatherReadings", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
